info:
  name: Get current application status by `application_id`
  type: http
  seq: 2
  tags:
    - application

http:
  method: GET
  url: "{{baseUrl}}/application/:application_id"
  params:
    - name: application_id
      value: ""
      type: path
      description: application_id value returned in in the `/application` response
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Successful response from the server
    request:
      url: "{{baseUrl}}/application/:application_id"
      method: GET
      params:
        - name: application_id
          value: ""
          type: path
          description: application_id value returned in in the `/application` response
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "application_status": "",
            "failed_cancelled_reason": "",
            "internal_score_status": "PASSED",
            "internal_id": ""
          }
